continue_task: True
with_hessian_eigenvalue_features: False
with_hessian_eigenvector_features: False
debug_mode: False
hidden_state_size: 20
n_meta_epochs: 128
meta_early_stopping: 128
classes_per_learner_set: 2
meta_batch_size: 16
learner_batch_size: 32
n_learner_batches: 32
backpropagation_depth: 8
backpropagation_padding: 4
learner_train_size: 32
learner_test_size: 96
n_train_sets: 128
n_test_sets: 128
meta_test_class_ratio: 0.3
initial_learner_lr: 0.05
n_meta_valid_steps: 128
dataset_key: "cifar100"
logging_level: "info"
random_seed: 12345
lr_schedule_epochs:
  - 0
  - 16
  - 64
lr_schedule_rates:
  - 0.01
  - 0.001
  - 0.0001
