continue_task: True
debug_mode: False
hidden_state_size: 20
n_meta_epochs: 128
meta_early_stopping: 128
lr_schedule: lr_schedule
classes_per_learner_set: 2
meta_batch_size: 8
learner_batch_size: 32
n_learner_batches: 64
backpropagation_depth: 32
backpropagation_padding: 4
learner_train_size: 32
learner_test_size: 96
n_train_sets: 64
n_test_sets: 64
meta_test_class_ratio: 0.3
initial_learner_lr: 0.015
n_meta_valid_steps: 64
dataset_key: "cifar100"
logging_level: "info"
lr_schedule_epochs:
  - 0
  - 8
  - 32
lr_schedule_rates:
  - 0.01
  - 0.001
  - 0.0001
